# Generated by Django 3.1.5 on 2021-01-06 12:16

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', markdownx.models.MarkdownxField()),
                ('priority', models.IntegerField()),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_date', models.DateField(blank=True, default='2021-01-01', null=True)),
            ],
        ),
    ]
